import Head from "next/head";
import {
  Container,
  Heading,
  Table,
  TableContainer,
  Thead,
  Tbody,
  Th,
  Tr,
  Td,
  Spinner,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { axiosInstance } from "@/lib/axios";
import { useQuery } from "@tanstack/react-query";

export default function Home() {
  const { data, isLoading } = useQuery({
    queryFn: async () => {
      const products = await axiosInstance.get("/products");
      return products;
    },
  });

  const renderProducts = () => {
    return data?.data.map((product, index) => {
      return (
        <Tr key={product.id}>
          <Td>{index + 1}</Td>
          <Td>{product.name}</Td>
          <Td>{product.price}</Td>
          <Td>{product.description}</Td>
          <Td>{product.image}</Td>
        </Tr>
      );
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Hello World</Heading>
          <TableContainer>
            <Table>
              <Thead>
                <Tr>
                  <Th>Id</Th>
                  <Th>Name</Th>
                  <Th>Price</Th>
                  <Th>description</Th>
                  <Th>image</Th>
                </Tr>
              </Thead>
              <Tbody>
                {isLoading && <Spinner />}
                {renderProducts()}
              </Tbody>
            </Table>
          </TableContainer>
        </Container>
      </main>
    </>
  );
}
